/* Mímica rioplatense: frases para actuar sin hablar.
   Antes de agregar: node tests/auditar-palabras.cjs --md */
window.MIMICA_FRASES=[
  "CEBAR UN MATE","ESPERAR EL ÓMNIBUS","PERDER EL ÓMNIBUS","TENDER LA ROPA","PRENDER EL FUEGO DEL ASADO","DAR VUELTA LA CARNE","CORTAR EL PASTO",
  "LAVAR LOS PLATOS","PLANCHAR UNA CAMISA","HACER LA CAMA","BARRER LA VEREDA","PASEAR AL PERRO","BAÑAR AL PERRO","SACAR LA BASURA",
  "CAMBIAR UN PAÑAL","DORMIR LA SIESTA","LEVANTARSE TARDE","APAGAR EL DESPERTADOR","LAVARSE LOS DIENTES","AFEITARSE","MAQUILLARSE",
  "PEINARSE","DUCHARSE CON AGUA FRÍA","PONERSE PROTECTOR SOLAR","ARMAR LA SOMBRILLA","NADAR EN EL MAR","HACER SURF","PESCAR EN LA RAMBLA",
  "ANDAR EN BICICLETA","ANDAR EN CABALLO","MANEJAR UN AUTO","ESTACIONAR EN BAJADA","CAMBIAR UNA RUEDA","CARGAR NAFTA","PEDIR UN TAXI",
  "SACAR UNA SELFIE","SACAR FOTOS EN UN CASAMIENTO","BAILAR CUMBIA","BAILAR TANGO","TOCAR EL TAMBOR","TOCAR LA GUITARRA","DIRIGIR UNA ORQUESTA",
  "CANTAR EN EL KARAOKE","FESTEJAR UN GOL","ATAJAR UN PENAL","HACER JUEGUITO CON LA PELOTA","HACER UNA CHILENA","SER ÁRBITRO Y SACAR TARJETA ROJA",
  "JUGAR AL TRUCO Y MENTIR","REPARTIR LAS CARTAS","TIRAR LOS DADOS","JUGAR A LA PLAYSTATION","MIRAR UN PARTIDO NERVIOSO","GRITAR EN LA TRIBUNA",
  "INFLAR UN GLOBO","SOPLAR LAS VELAS","ABRIR UN REGALO QUE NO TE GUSTÓ","ENVOLVER UN REGALO","DESTAPAR UNA BOTELLA","BRINDAR","SERVIR UN VINO",
  "COMER UN CHORIPÁN","COMER UN HELADO QUE SE DERRITE","PELAR UNA CEBOLLA Y LLORAR","CORTAR UNA PIZZA","AMASAR TORTAS FRITAS","FREÍR UN HUEVO",
  "PAGAR CON TARJETA Y QUE NO PASE","HACER COLA EN EL BANCO","BUSCAR LAS LLAVES","QUEDARSE ENCERRADO EN EL BAÑO","QUEDARSE SIN BATERÍA",
  "MANDAR UN AUDIO DE WHATSAPP","HABLAR POR TELÉFONO SIN SEÑAL","BUSCAR WIFI","MIRAR UNA PELÍCULA DE TERROR","LLORAR CON UNA NOVELA",
  "ESTORNUDAR","TENER HIPO","PISAR UNA BABOSA","MATAR UN MOSQUITO","ESCAPAR DE UNA ABEJA","RESBALARSE EN EL HIELO","SUBIR UNA ESCALERA CON BOLSAS",
  "EMPUJAR UN AUTO QUE NO ARRANCA","ARMAR UN MUEBLE SIN INSTRUCCIONES","COLGAR UN CUADRO","PINTAR UNA PARED","ABRIR UN FRASCO QUE NO SE ABRE",
  "HACER YOGA","LEVANTAR PESAS","SALTAR LA CUERDA","CORRER UNA MARATÓN","HACER ABDOMINALES","ESQUIAR","PATINAR SOBRE HIELO"
];
