/* Mímica rioplatense: frases para actuar sin hablar, en 3 niveles.
   MIMICA_FRASES = fácil (+1), MIMICA_MEDIA = media (+2), MIMICA_DIFICIL = difícil (+3).
   Antes de agregar: node tests/auditar-palabras.cjs --md */
window.MIMICA_FRASES=[
  "CEBAR UN MATE","ESPERAR EL ÓMNIBUS","PERDER EL ÓMNIBUS","TENDER LA ROPA","PRENDER EL FUEGO DEL ASADO","DAR VUELTA LA CARNE","CORTAR EL PASTO",
  "LAVAR LOS PLATOS","PLANCHAR UNA CAMISA","HACER LA CAMA","BARRER LA VEREDA","PASEAR AL PERRO","BAÑAR AL PERRO","SACAR LA BASURA",
  "CAMBIAR UN PAÑAL","DORMIR LA SIESTA","LEVANTARSE TARDE","APAGAR EL DESPERTADOR","LAVARSE LOS DIENTES","AFEITARSE","MAQUILLARSE",
  "PEINARSE","DUCHARSE CON AGUA FRÍA","PONERSE PROTECTOR SOLAR","ARMAR LA SOMBRILLA","NADAR EN EL MAR","HACER SURF","PESCAR EN LA RAMBLA",
  "ANDAR EN BICICLETA","ANDAR EN CABALLO","MANEJAR UN AUTO","ESTACIONAR EN BAJADA","CAMBIAR UNA RUEDA","CARGAR NAFTA","PEDIR UN TAXI",
  "SACAR UNA SELFIE","SACAR FOTOS EN UN CASAMIENTO","BAILAR CUMBIA","BAILAR TANGO","TOCAR EL TAMBOR","TOCAR LA GUITARRA","DIRIGIR UNA ORQUESTA",
  "CANTAR EN EL KARAOKE","FESTEJAR UN GOL","ATAJAR UN PENAL","HACER JUEGUITO CON LA PELOTA","HACER UNA CHILENA","SER ÁRBITRO Y SACAR TARJETA ROJA",
  "JUGAR AL TRUCO Y MENTIR","REPARTIR LAS CARTAS","TIRAR LOS DADOS","JUGAR A LA PLAYSTATION","MIRAR UN PARTIDO NERVIOSO","GRITAR EN LA TRIBUNA",
  "INFLAR UN GLOBO","SOPLAR LAS VELAS","ABRIR UN REGALO QUE NO TE GUSTÓ","ENVOLVER UN REGALO","DESTAPAR UNA BOTELLA","BRINDAR","SERVIR UN VINO",
  "COMER UN CHORIPÁN","COMER UN HELADO QUE SE DERRITE","PELAR UNA CEBOLLA Y LLORAR","CORTAR UNA PIZZA","AMASAR TORTAS FRITAS","FREÍR UN HUEVO",
  "PAGAR CON TARJETA Y QUE NO PASE","HACER COLA EN EL BANCO","BUSCAR LAS LLAVES","QUEDARSE ENCERRADO EN EL BAÑO","QUEDARSE SIN BATERÍA",
  "MANDAR UN AUDIO DE WHATSAPP","HABLAR POR TELÉFONO SIN SEÑAL","BUSCAR WIFI","MIRAR UNA PELÍCULA DE TERROR","LLORAR CON UNA NOVELA",
  "ESTORNUDAR","TENER HIPO","PISAR UNA BABOSA","MATAR UN MOSQUITO","ESCAPAR DE UNA ABEJA","RESBALARSE EN EL HIELO","SUBIR UNA ESCALERA CON BOLSAS",
  "EMPUJAR UN AUTO QUE NO ARRANCA","ARMAR UN MUEBLE SIN INSTRUCCIONES","COLGAR UN CUADRO","PINTAR UNA PARED","ABRIR UN FRASCO QUE NO SE ABRE",
  "HACER YOGA","LEVANTAR PESAS","SALTAR LA CUERDA","CORRER UNA MARATÓN","HACER ABDOMINALES","ESQUIAR","PATINAR SOBRE HIELO"
];
/* Media (+2): películas, series, deportes y personajes en acción. */
window.MIMICA_MEDIA=[
  "TITANIC","JURASSIC PARK","TOY STORY","EL REY LEÓN","STAR WARS","EL SEÑOR DE LOS ANILLOS","MISIÓN IMPOSIBLE","RÁPIDOS Y FURIOSOS",
  "LA CASA DE PAPEL","STRANGER THINGS","EL JUEGO DEL CALAMAR","KING KONG","FROZEN","AVATAR","MATRIX","KARATE KID",
  "LOS CAZAFANTASMAS","LOS INCREÍBLES","MI POBRE ANGELITO","E.T.","PIRATAS DEL CARIBE","LA BELLA Y LA BESTIA","MARY POPPINS","EL EXORCISTA",
  "GODZILLA","LOS PITUFOS","TOP GUN","GREASE","EL PADRINO","GRAN HERMANO","EL CHAPULÍN COLORADO","CASI ÁNGELES",
  "SALTO CON GARROCHA","LANZAMIENTO DE JABALINA","NADO SINCRONIZADO","CURLING","ESGRIMA","CLAVADOS","POLO","REMO",
  "TIRO CON ARCO","GIMNASIA ARTÍSTICA","SALTO EN PARACAÍDAS","PARAPENTE","BUNGEE JUMPING","SUMO","LUCHA LIBRE","PATINAJE ARTÍSTICO",
  "UN DOMADOR DE LEONES","UN DJ EN UN BOLICHE","UN MOZO CON UNA BANDEJA LLENA","UN CIRUJANO OPERANDO","UN MAGO QUE SACA UN CONEJO","UN ASTRONAUTA EN LA LUNA","UN BOMBERO APAGANDO UN INCENDIO","UN PIRATA CON PATA DE PALO",
  "UN ZOMBI","UNA MOMIA","UN VAMPIRO","UNA SIRENA","UN SUPERHÉROE VOLANDO","UN CAVERNÍCOLA","UN TORERO","UN EQUILIBRISTA EN LA CUERDA",
  "UN DIRECTOR DE CINE","UN PELUQUERO CORTANDO EL PELO","UN DOCTOR VACUNANDO","UN LOCUTOR DE FÚTBOL","UN VENDEDOR DE HELADOS","UN GUARDIA REAL INGLÉS","UN SAMURÁI","UN MOTOQUERO EN LA RUTA"
];
/* Difícil (+3): cosas concretas que se adivinan pero cuesta actuar. */
window.MIMICA_DIFICIL=[
  "UN PEREZOSO","UN AVESTRUZ","UN ESCORPIÓN","UN ARMADILLO","UN PICAFLOR","UN CISNE","UN ERIZO","UNA TORTUGA DADA VUELTA","UN CANGREJO","UN TUCÁN",
  "UNA MEDUSA","UN ORNITORRINCO","UN PERRO SALCHICHA","UNA LANGOSTA","UN GUSANO","UN ASCENSOR","UN SAPO","UNA ANACONDA","UN ELEFANTE MARINO","UN HÁMSTER EN SU RUEDITA",
  "UNA ESCALERA MECÁNICA","UNA CAJA FUERTE","UN MOLINO DE VIENTO","UN PERRO MOJADO","UNA MÁQUINA DE COSER","UN TORNADO","UN ARCOÍRIS","UNA IMPRESORA","UNA MONTAÑA RUSA","LOS AUTITOS CHOCADORES",
  "UN VENTILADOR DE TECHO","UNA BATIDORA","UN SECARROPAS","UN RELOJ CUCÚ","UNA BICICLETA FIJA","UNA VUELTA AL MUNDO","UNA AVALANCHA","UNA PUERTA GIRATORIA","UN CAJERO AUTOMÁTICO","UNA CORTADORA DE PASTO",
  "UN TOPO CAVANDO","ENHEBRAR UNA AGUJA","UN PINGÜINO TIRÁNDOSE AL AGUA","HACER EL NUDO DE LA CORBATA","UN EXTINTOR","ARMAR UN CUBO MÁGICO","UN BANDONEÓN","PESCAR UN PESCADO GRANDE","UNA HAMACA PARAGUAYA","CAMINAR SOBRE BRASAS",
  "UN VENTRÍLOCUO","UN HOMBRE ESTATUA","UN LIMPIAVIDRIOS COLGADO","UN APICULTOR","UN HIPNOTIZADOR","UN TITIRITERO","UNA FILA DE DOMINÓ CAYENDO","UN YOYÓ","UN FAQUIR","UN ESPANTAPÁJAROS"
];
