const PalabraSecreta=(()=>{
  const CLAVE="gya_palabra_secreta",MAX=6,COLORES={ausente:"⬛",presente:"🟨",exacta:"🟩"};
  let datos=cargar(),raiz=null,partida=null,borrador="",practica=false,animando=false,token=0,duelo=false;
  let audioMusica=null;
  function iniciarMusicaJuego(){
    try{
      if(typeof sonidoPermitido==="function"&&!sonidoPermitido())return;
      if(!audioMusica){audioMusica=new Audio("assets/audio/palabra-secreta-musica.mp3");audioMusica.loop=true;audioMusica.volume=.28;}
      if(audioMusica.paused)audioMusica.play().catch(()=>{});
    }catch(e){}
  }
  function detenerMusicaJuego(){try{if(audioMusica&&!audioMusica.paused)audioMusica.pause();}catch(e){}}
  function alVisibilidad(){if(document.hidden)detenerMusicaJuego();else{iniciarMusicaJuego();comprobarDia();}}
  function cargar(){try{const d=JSON.parse(localStorage.getItem(CLAVE)||"null");if(d&&typeof d==="object")return{diaria:d.diaria||null,racha:Number(d.racha)||0,mejorRacha:Number(d.mejorRacha)||0,ganadas:Number(d.ganadas)||0,jugadas:Number(d.jugadas)||0,distribucion:Array.isArray(d.distribucion)?d.distribucion.slice(0,6):[0,0,0,0,0,0],ultimoGanado:Number(d.ultimoGanado)||0,ayudaVista:!!d.ayudaVista};}catch(e){}return{diaria:null,racha:0,mejorRacha:0,ganadas:0,jugadas:0,distribucion:[0,0,0,0,0,0],ultimoGanado:0,ayudaVista:false};}
  function guardar(){try{localStorage.setItem(CLAVE,JSON.stringify(datos));}catch(e){}}
  function indiceDia(fecha=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Montevideo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(fecha).map(x=>[x.type,x.value]));return Math.floor(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day))/86400000);}
  function palabraDia(dia=indiceDia()){return PALABRA_SECRETAS[dia%PALABRA_SECRETAS.length];}
  function rachaActual(){return datos.ultimoGanado>=indiceDia()-1?datos.racha:0;}
  function evaluar(intento,solucion){const r=Array(5).fill("ausente"),sobrantes={};for(let i=0;i<5;i++){if(intento[i]===solucion[i])r[i]="exacta";else sobrantes[solucion[i]]=(sobrantes[solucion[i]]||0)+1;}for(let i=0;i<5;i++)if(r[i]!=="exacta"&&sobrantes[intento[i]]>0){r[i]="presente";sobrantes[intento[i]]--;}return r;}
  function nueva(objetivo){return{objetivo,intentos:[],terminada:false,gano:false};}
  function iniciarDiaria(){const dia=indiceDia();if(!datos.diaria||datos.diaria.dia!==dia){datos.diaria={dia,...nueva(palabraDia(dia))};guardar();}partida=datos.diaria;practica=false;borrador="";}
  function pantalla(){raiz.innerHTML='<div class="ps-game"><button type="button" class="ext-volver" id="psVolver">⟵ Extensiones</button><div class="ps-top"><div><h2>Palabra Secreta</h2><p class="ps-aviso">💡 Tocá "?" para ver cómo se juega</p></div><button type="button" id="psEstadisticas" aria-label="Estadísticas">▥</button><button type="button" id="psAyuda" aria-label="Cómo se juega">?</button></div><div class="ps-stats" id="psStats"></div><div class="ps-tablero" id="psTablero" aria-label="Tablero de seis intentos"></div><div class="ps-mensaje" id="psMensaje" aria-live="polite"></div><div class="ps-teclado" id="psTeclado"></div><div class="ps-acciones"><button type="button" id="psEnviar">Enviar</button><button type="button" id="psBorrar">Borrar</button></div><button type="button" class="ps-duelo" id="psDuelo">👥 Jugar con un amigo</button><div class="ps-final" id="psFinal" hidden></div><div class="sf-panel-capa" id="psAyudaPanel" hidden></div></div>';raiz.querySelector("#psVolver").onclick=()=>Extensiones.abrirLobby();raiz.querySelector("#psAyuda").onclick=ayuda;raiz.querySelector("#psEstadisticas").onclick=mostrarEstadisticas;raiz.querySelector("#psEnviar").onclick=enviar;raiz.querySelector("#psBorrar").onclick=()=>tecla("Backspace");raiz.querySelector("#psDuelo").onclick=iniciarDuelo;}
  function ayuda(){const p=raiz.querySelector("#psAyudaPanel");p.innerHTML='<div class="sf-panel"><h3>¿Cómo se juega?</h3><p>Tenés 6 intentos para descubrir una palabra de 5 letras. Escribí una palabra real y tocá Enviar. Verde: letra en el lugar correcto. Amarillo: letra en otro lugar. Gris: letra que no está.</p><p><b>Ojo:</b> la palabra puede tener una letra repetida (por ejemplo, dos E). Si la escribís dos veces, cada aparición se marca por separado según corresponda.</p><div class="ps-ejemplo"><span class="exacta">A</span><span class="presente">S</span><span class="ausente">A</span><span class="ausente">D</span><span class="ausente">O</span></div><div class="sf-acciones"><button type="button" class="sf-principal">Entendido</button></div></div>';p.hidden=false;p.querySelector("button").onclick=()=>{p.hidden=true;datos.ayudaVista=true;guardar();};}
  function mostrarEstadisticas(){const p=raiz.querySelector("#psAyudaPanel");p.innerHTML='<div class="sf-panel"><h3>Estadísticas</h3><p id="psResumen"></p><div id="psDistribucion" class="ps-distribucion"></div><div class="sf-acciones"><button type="button" class="sf-principal">Cerrar</button></div></div>';p.querySelector("#psResumen").textContent=`Jugadas: ${datos.jugadas} · Ganadas: ${datos.ganadas} · Racha: ${rachaActual()} · Mejor: ${datos.mejorRacha}`;const d=p.querySelector("#psDistribucion");for(let i=0;i<6;i++){const fila=document.createElement("div");fila.textContent=`${i+1} intento${i?"s":""}: ${datos.distribucion[i]||0}`;d.appendChild(fila);}p.hidden=false;p.querySelector("button").onclick=()=>p.hidden=true;}
  function mensaje(txt){if(raiz)raiz.querySelector("#psMensaje").textContent=txt;}
  function estadisticas(){const s=raiz.querySelector("#psStats");s.textContent=`Racha: ${rachaActual()} · Mejor: ${datos.mejorRacha} · Ganadas: ${datos.ganadas}`;}
  function teclado(){const t=raiz.querySelector("#psTeclado");t.replaceChildren();const estado={};for(const x of partida.intentos)for(let i=0;i<5;i++){const k=x.palabra[i],e=x.colores[i];if(!estado[k]||({ausente:0,presente:1,exacta:2})[e]>({ausente:0,presente:1,exacta:2})[estado[k]])estado[k]=e;}for(const fila of ["QWERTYUIOP","ASDFGHJKL","ZXCVBNM"]){const d=document.createElement("div");d.className="ps-teclado-fila";for(const l of fila){const b=document.createElement("button");b.type="button";b.textContent=l;b.className=estado[l]||"";b.setAttribute("aria-label","Letra "+l);b.onclick=()=>tecla(l);d.appendChild(b);}t.appendChild(d);}}
  function tablero(){const t=raiz.querySelector("#psTablero");t.replaceChildren();for(let fila=0;fila<MAX;fila++){const d=document.createElement("div");d.className="ps-fila";const jugada=partida.intentos[fila],texto=jugada?.palabra||(fila===partida.intentos.length&&!partida.terminada?borrador:"");for(let i=0;i<5;i++){const celda=document.createElement("span");celda.className="ps-celda"+(jugada?" "+jugada.colores[i]:"");celda.textContent=texto[i]||"";d.appendChild(celda);}t.appendChild(d);}teclado();estadisticas();final();}
  function final(){const f=raiz.querySelector("#psFinal");f.replaceChildren();f.hidden=!partida.terminada;if(!partida.terminada)return;const p=document.createElement("p");p.textContent=partida.gano?`¡La encontraste en ${partida.intentos.length} intento${partida.intentos.length===1?"":"s"}!`:`La palabra era ${partida.objetivo}.`;f.appendChild(p);if(duelo)return;const compartir=document.createElement("button");compartir.type="button";compartir.textContent="📲 Compartir por WhatsApp";compartir.onclick=compartirWhatsApp;f.appendChild(compartir);const copiar=document.createElement("button");copiar.type="button";copiar.textContent="Copiar resultado";copiar.onclick=compartirResultado;f.appendChild(copiar);if(!practica){const jugar=document.createElement("button");jugar.type="button";jugar.textContent="Jugar otra palabra";jugar.onclick=iniciarPractica;f.appendChild(jugar);}else{const volver=document.createElement("button");volver.type="button";volver.textContent="Volver a la palabra de hoy";volver.onclick=()=>{iniciarDiaria();tablero();mensaje("");};f.appendChild(volver);}}
  function comprobarDia(){if(raiz&&!practica&&partida.dia!==indiceDia()){iniciarDiaria();tablero();mensaje("Ya está disponible la palabra de hoy.");return true;}return false;}
  function tecla(valor){if(!raiz||comprobarDia()||partida.terminada||animando)return;if(valor==="Backspace"){borrador=borrador.slice(0,-1);tablero();return;}if(valor==="Enter"){enviar();return;}const l=valor.toUpperCase();if(/^[A-Z]$/.test(l)&&borrador.length<5){borrador+=l;tablero();if(typeof tac==="function")tac();}}
  function enviar(){if(!raiz||comprobarDia()||partida.terminada||animando)return;if(borrador.length!==5){mensaje("Escribí cinco letras.");return;}if(!PALABRA_VALIDAS.has(borrador)&&!PALABRA_SECRETAS.includes(borrador)){mensaje("Esa palabra no está en el diccionario.");return;}const colores=evaluar(borrador,partida.objetivo);const jugada={palabra:borrador,colores};partida.intentos.push(jugada);borrador="";partida.gano=jugada.palabra===partida.objetivo;partida.terminada=partida.gano||partida.intentos.length>=MAX;if(partida.terminada&&!practica){datos.jugadas++;if(partida.gano){datos.ganadas++;datos.distribucion[partida.intentos.length-1]=(datos.distribucion[partida.intentos.length-1]||0)+1;datos.racha=datos.ultimoGanado===partida.dia-1?datos.racha+1:1;datos.mejorRacha=Math.max(datos.mejorRacha,datos.racha);datos.ultimoGanado=partida.dia;if(typeof objSumar==="function")objSumar("palabraDiaria",1);if(typeof logroDesbloquear==="function"){logroDesbloquear("palabraPrimera");if(partida.intentos.length<=2)logroDesbloquear("palabraRapida");if(datos.racha>=7)logroDesbloquear("palabraRacha");}}else datos.racha=0;}if(!practica)guardar();if(typeof bip==="function")bip(partida.gano?900:500,.09);mensaje("");tablero();if(duelo)progresoDuelo();const ultima=raiz.querySelectorAll(".ps-fila")[partida.intentos.length-1];if(!matchMedia("(prefers-reduced-motion: reduce)").matches){animando=true;ultima.querySelectorAll(".ps-celda").forEach((c,i)=>{c.style.animationDelay=i*.12+"s";c.classList.add("voltear");});const t=++token;setTimeout(()=>{if(t===token)animando=false;},850);}try{if(typeof vibrar==="function")vibrar(20);}catch(e){}}
  function textoCompartir(){const d=practica?"ronda extra":new Intl.DateTimeFormat("es-UY",{timeZone:"UTC",day:"numeric",month:"numeric"}).format(new Date(partida.dia*86400000));return`Palabra Secreta ${d} ${partida.gano?partida.intentos.length:"X"}/6\n${partida.intentos.map(x=>x.colores.map(c=>COLORES[c]).join("")).join("\n")}`;}
  async function compartirResultado(){const txt=textoCompartir();try{await navigator.clipboard.writeText(txt);mensaje("Resultado copiado. ¡Compartilo!");}catch(e){const a=document.createElement("textarea");a.value=txt;document.body.appendChild(a);a.select();const ok=document.execCommand("copy");a.remove();mensaje(ok?"Resultado copiado. ¡Compartilo!":"No se pudo copiar el resultado.");}}
  function compartirWhatsApp(){let base="";try{base=location.origin+location.pathname;}catch(e){}try{window.open("https://wa.me/?text="+encodeURIComponent(textoCompartir()+"\n¿Te animás? Jugá gratis en Girá y Adiviná: "+base),"_blank");}catch(e){}}
  /* Duelo 1 vs 1: los dos adivinan la MISMA palabra (no la del día).
     Puntos = 7 − intentos si la encontrás (0 si no): gana quien la saca en menos intentos. */
  const ptsDuelo=()=>partida.gano?7-partida.intentos.length:0;
  function progresoDuelo(){
    Duelo.enviarProgreso({n:partida.intentos.length,gano:partida.gano});
    if(partida.terminada){
      Duelo.enviarFinal({valor:ptsDuelo()});
      setTimeout(()=>Duelo.mostrarResultado({valor:ptsDuelo()},{etiqueta:"puntos: 7 − intentos (0 si no la encontrás)",onVolver:()=>{duelo=false;practica=false;if(raiz){iniciarDiaria();tablero();mensaje("");}}}),900);
    }
  }
  function iniciarDuelo(){
    if(typeof Duelo==="undefined")return;
    Duelo.mostrarLobby("Palabra Secreta","palabra",{detalle:"Los dos adivinan la <b>misma palabra</b>, cada uno en su tablero. Gana el que la descubre en <b>menos intentos</b>.",onListo:soyHost=>{
      const arrancar=w=>{duelo=true;practica=true;partida=nueva(w);borrador="";Duelo.mostrarBadge();Duelo.actualizarBadge("0/6");if(raiz){raiz.querySelector("#psAyudaPanel").hidden=true;tablero();mensaje("👥 Duelo: misma palabra para los dos.");}};
      Duelo.onProgresoRival(p=>Duelo.actualizarBadge((p.gano?"✓ ":"")+(Number(p.n)||0)+"/6"));
      if(soyHost){const cand=PALABRA_SECRETAS.filter(w=>w!==palabraDia());const w=cand[Math.floor(Math.random()*cand.length)];Duelo.enviarRonda({palabra:w});arrancar(w);}
      else Duelo.onRondaRecibida(d=>{if(typeof d.palabra==="string"&&d.palabra.length===5)arrancar(d.palabra.toUpperCase());});
    }});
  }
  function iniciarPractica(){practica=true;const candidatas=PALABRA_SECRETAS.filter(w=>w!==palabraDia());partida=nueva(candidatas[Math.floor(Math.random()*candidatas.length)]);borrador="";tablero();mensaje("Palabra extra: no modifica tu racha de hoy.");}
  function abrir(contenedor){salir();raiz=contenedor;iniciarDiaria();pantalla();tablero();document.addEventListener("visibilitychange",alVisibilidad);iniciarMusicaJuego();if(!datos.ayudaVista)ayuda();}
  function salir(){token++;animando=false;if(duelo&&typeof Duelo!=="undefined")Duelo.salir();duelo=false;document.removeEventListener("visibilitychange",alVisibilidad);detenerMusicaJuego();raiz=null;partida=null;borrador="";}
  return{abrir,salir,tecla,indiceDia,palabraDia,evaluar,rachaActual,estadisticasGuardadas:()=>({...datos}),textoCompartir};
})();
window.PalabraSecreta=PalabraSecreta;
