/* Trabalenguas contra reloj: n = nivel (1 cortos, 2 medianos, 3 largos).
   Antes de agregar: node tests/auditar-palabras.cjs --md */
window.TRABALENGUAS=[
  {n:1,t:"Tres tristes tigres tragaban trigo en un trigal."},
  {n:1,t:"Pablito clavó un clavito. ¿Qué clavito clavó Pablito?"},
  {n:1,t:"Mi mamá me mima mucho."},
  {n:1,t:"Como poco coco como, poco coco compro."},
  {n:1,t:"Pepe Pecas pica papas con un pico."},
  {n:1,t:"Erre con erre cigarro, erre con erre barril."},
  {n:1,t:"Juan junta juncos junto a la zanja."},
  {n:1,t:"Pancha plancha con cuatro planchas."},
  {n:1,t:"Compré pocas copas, pocas copas compré."},
  {n:1,t:"Hoy ya es ayer y ayer ya es hoy."},
  {n:1,t:"El chivito de Chicho chorrea chimichurri."},
  {n:1,t:"Marta mete el mate en la mochila de Mateo."},
  {n:1,t:"Pocas pecas pinta Paca."},
  {n:1,t:"Lola lava la lona lila."},
  {n:1,t:"Rosa Rizo reza el rosario."},
  {n:1,t:"Tito tiene tres tambores para tocar."},
  {n:1,t:"Susi sale sola sin sombrilla."},
  {n:1,t:"Chancho chico chilla en el chiquero."},
  {n:1,t:"Bruno brinca bravo en el barro."},
  {n:1,t:"Cuca cuida cuatro cucos en la cuna."},
  {n:2,t:"Si Sansón no sazona su salsa con sal, le sale sosa."},
  {n:2,t:"Cuando cuentes cuentos, cuenta cuántos cuentos cuentas."},
  {n:2,t:"Poquito a poquito Paquito empaca poquitas copitas en este paquete."},
  {n:2,t:"El hipopótamo Hipo está con hipo. ¿Quién le quita el hipo al hipopótamo Hipo?"},
  {n:2,t:"Me han dicho que has dicho un dicho que han dicho que he dicho yo."},
  {n:2,t:"Treinta y tres trenes trajeron trigo a Treinta y Tres."},
  {n:2,t:"El rey de Constantinopla se quiere descontantinopolizar."},
  {n:2,t:"Ñoño Yáñez come ñame en las mañanas con el niño."},
  {n:2,t:"Chorizo chiquito, chiquito chorizo, el chorizo del chico es el más chiquito."},
  {n:2,t:"Busca el bosque Francisco, un vasco bizco muy brusco."},
  {n:2,t:"Debajo del puente de Guadalajara había un conejo debajo del agua."},
  {n:2,t:"Rápido ruedan los carros cargados de azúcar del ferrocarril."},
  {n:2,t:"Ramiro Ramírez rema rápido por el río Uruguay."},
  {n:2,t:"La bruja Brujilda brinca brincos bruscos con su escoba."},
  {n:2,t:"Mariano Mariño Marín mira la marea de Maldonado."},
  {n:2,t:"Pedro pide pan, Pancho pide pollo y Paula pide papas."},
  {n:2,t:"Un limón y medio limón, dos limones y medio limón."},
  {n:2,t:"Camarón, caramelo, camarón, caramelo, camarón, caramelo."},
  {n:2,t:"Toto toma té, Tita toma mate y yo me tomo mi taza de chocolate."},
  {n:2,t:"Pepe puso un peso en el piso del pozo; en el piso del pozo Pepe puso un peso."},
  {n:3,t:"El cielo está enladrillado, ¿quién lo desenladrillará? El desenladrillador que lo desenladrille, buen desenladrillador será."},
  {n:3,t:"Parra tenía una perra y Guerra tenía una parra; la perra de Parra subió a la parra de Guerra."},
  {n:3,t:"Pedro Pérez Pereira, pobre pintor portugués, pinta paisajes por poca plata para pasar por París."},
  {n:3,t:"Tengo una gallina pinta, pipiripinta, gorda, pipirigorda, que tiene tres pollitos pintos, pipiripintos, gordos, pipirigordos."},
  {n:3,t:"Si tu gusto gustara del gusto que gusta mi gusto, mi gusto gustaría del gusto que gusta tu gusto."},
  {n:3,t:"Cómo querés que te quiera si el que quiero que me quiera no me quiere como quiero que me quiera."},
  {n:3,t:"Yo tengo una cabra ética, perlética, pelapelambrética, pelúa, pelambrúa, que tiene un cabrito ético, perlético, pelapelambrético."},
  {n:3,t:"El amor es una locura que solo el cura lo cura, pero el cura que lo cura comete una gran locura."},
  {n:3,t:"En la caja de Cacho hay cuatro cuadernos, cuatro cuadros, cuatro cucharas y un cuchillo."},
  {n:3,t:"Del Cerro al Prado y del Prado al Cerro corre el perro de Ferro con un fierro."},
  {n:3,t:"El otorrinolaringólogo de Parangaricutirimícuaro se quiere desotorrinolaringologoparangaricutirimicuarizar."},
  {n:3,t:"Chicho chupa la bombilla, la bombilla chupa Chicho; si la bombilla no chupa, ¿qué chupará Chicho?"},
  {n:3,t:"Pancho Plancha planchó prolijos pantalones para pasear por la plaza de Paysandú."},
  {n:3,t:"Un tubo tiró un tubo y otro tubo lo detuvo; hay tubos que tienen tubos pero este tubo tubo no tuvo."},
  {n:3,t:"Pepa Pérez peina peinados peculiares para pelucas parecidas a las de las princesas."},
  {n:3,t:"Cruzando el río Negro, el negro Rogelio rugía y rogaba a Rosario que remara rápido."},
  {n:3,t:"Si el caracol tuviera cara como tiene el caracol, fuera cara, fuera col, fuera caracol con cara."},
  {n:3,t:"Doña Díaz dice que diez dedos de dos manos dan diez dedos."},
  {n:3,t:"Paco Peco, chico rico, insultaba como un loco a su tío Federico, y este dijo: poco a poco, Paco Peco, poco pico."},
  {n:3,t:"Al tren de Treinta y Tres trepan tres tristes trapecistas con tres trapos y tres trompetas."}
];
